import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Image from 'next/image'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center px-6 py-4 border-b">
          <Image src="/logo.png" alt="东方食品 Logo" width={48} height={48} />
          <h1 className="text-green-600 text-xl font-bold ml-4">
            DongFang Food 东方食品
          </h1>
        </header>
        
        {children}
      </body>
    </html>
  );
}
